services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INDEX_BACKEND=qdrant
      - QDRANT_URL=http://qdrant:6333
      - LLM_MODE=local
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./:/app

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./:/app

volumes:
  qdrant_storage:

